#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cachecontrol', 'cachecontrol.caches']

package_data = \
{'': ['*']}

install_requires = \
['requests >= 2.16.0', 'msgpack >= 0.5.2, < 2.0.0']

extras_require = \
{'dev': ['CacheControl[filecache,redis]',
         'build',
         'cherrypy',
         'codespell[tomli]',
         'furo',
         'mypy',
         'pytest',
         'pytest-cov',
         'ruff',
         'sphinx',
         'sphinx-copybutton',
         'tox',
         'types-redis',
         'types-requests'],
 'filecache': ['filelock >= 3.8.0'],
 'redis': ['redis>=2.10.5']}

entry_points = \
{'console_scripts': ['doesitcache = cachecontrol._cmd:main']}

setup(name='CacheControl',
      version='0.14.1',
      description='httplib2 caching for requests',
      author=None,
      author_email='Eric Larson <ericlarson@ionrock.com>, Frost Ming <me@frostming.com>, William Woodruff <william@yossarian.net>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.8',
     )
